language: cpp
#sudo: false

matrix:
  include:
    # - env: BUILD_TYPE=Debug
    #   os: osx
    #   osx_image: xcode8
    #   compiler: clang
    # - env: BUILD_TYPE=Release
    #   os: osx
    #   osx_image: xcode8
    #   compiler: clang

    # clang-3.6 32
#    - env: CLANG_VERSION=3.6 BUILD_TYPE=Debug ARCH=32
#      os: linux
#      addons: &clang36-32
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.6
#            - linux-libc-dev:i386
#            - g++-multilib
#            - gcc-multilib
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#
#    - env: CLANG_VERSION=3.6 BUILD_TYPE=Release ARCH=32
#      os: linux
#      addons: *clang36-32
#
#     clang-3.6 64
#    - env: CLANG_VERSION=3.6 BUILD_TYPE=Debug ARCH=64
#      os: linux
#      addons: &clang36-64
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.6
#            - g++
#            - gcc
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.6
#
#    - env: CLANG_VERSION=3.6 BUILD_TYPE=Release ARCH=64
#      os: linux
#      addons: *clang36-64

    # clang-3.7 32
#    - env: CLANG_VERSION=3.7 BUILD_TYPE=Debug ARCH=32
#      os: linux
#      addons: &clang37-32
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.7
#            - linux-libc-dev:i386
#            - g++-multilib
#            - gcc-multilib
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#
#    - env: CLANG_VERSION=3.7 BUILD_TYPE=Release ARCH=32
#      os: linux
#      addons: *clang37-32
#
#    # clang-3.7 64
#    - env: CLANG_VERSION=3.7 BUILD_TYPE=Debug ARCH=64
#      os: linux
#      addons: &clang37-64
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.7
#            - g++
#            - gcc
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#
#    - env: CLANG_VERSION=3.7 BUILD_TYPE=Release ARCH=64
#      os: linux
#      addons: *clang37-64
#
#
#    # clang-3.8 32
#    - env: CLANG_VERSION=3.8 BUILD_TYPE=Debug ARCH=32
#      os: linux
#      addons: &clang38-32
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.8
#            - linux-libc-dev:i386
#            - g++-multilib
#            - gcc-multilib
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#
#    - env: CLANG_VERSION=3.8 BUILD_TYPE=Release ARCH=32
#      os: linux
#      addons: *clang38-32
#
#    # clang-3.8 64
#    - env: CLANG_VERSION=3.8 BUILD_TYPE=Debug ARCH=64
#      os: linux
#      addons: &clang38-64
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - clang-3.8
#            - g++
#            - gcc
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.8
#
#    - env: CLANG_VERSION=3.8 BUILD_TYPE=Release ARCH=64
#      os: linux
#      addons: *clang38-64

    # clang-3.9
#    - env: CLANG_VERSION=3.9 BUILD_TYPE=Debug
#      os: linux
#      addons: &clang39
#        apt:
#          packages:
            # - cmake
            # - cmake-data
#            - clang-3.9
#            - g++-5
#          sources: &sources
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise
#    - env: CLANG_VERSION=3.9 BUILD_TYPE=Release
#      os: linux
#      addons: *clang39

    # gcc-4.9 32
#    - env: GCC_VERSION=4.9 BUILD_TYPE=Debug ARCH=32
#      os: linux
#      addons: &gcc49-32
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - linux-libc-dev:i386
#            - g++-4.9-multilib
#            - gcc-4.9-multilib
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#    - env: GCC_VERSION=4.9 BUILD_TYPE=Release ARCH=32
#      os: linux
#      addons: *gcc49-32
#
#    # gcc-4.9 64
#    - env: GCC_VERSION=4.9 BUILD_TYPE=Debug ARCH=64
#      os: linux
#      addons: &gcc49-64
#        apt:
#          packages:
#            - cmake
#            - cmake-data
#            - g++-4.9
#            - gcc-4.9
#          sources:
#            - george-edison55-precise-backports
#            - ubuntu-toolchain-r-test
#    - env: GCC_VERSION=4.9 BUILD_TYPE=Release ARCH=64
#      os: linux
#      addons: *gcc49-64
#
    # gcc-5 32
    # - env: GCC_VERSION=5 BUILD_TYPE=Debug ARCH=32
    #   os: linux
    #   addons: &gcc5-32
    #     apt:
    #       packages:
    #         - cmake
    #         - cmake-data
    #         - linux-libc-dev:i386
    #         - g++-5-multilib
    #         - gcc-5-multilib
    #       sources:
    #         - george-edison55-precise-backports
    #         - ubuntu-toolchain-r-test
    # - env: GCC_VERSION=5 BUILD_TYPE=Release ARCH=32
    #   os: linux
    #   addons: *gcc5-32

    # # gcc-5 64
    # - env: GCC_VERSION=5 BUILD_TYPE=Debug ARCH=64
    #   os: linux
    #   addons: &gcc5-64
    #     apt:
    #       packages:
    #         - cmake
    #         - cmake-data
    #         - g++-5
    #         - gcc-5
    #       sources:
    #         - george-edison55-precise-backports
    #         - ubuntu-toolchain-r-test
    # - env: GCC_VERSION=5 BUILD_TYPE=Release ARCH=64
    #   os: linux
    #   addons: *gcc5-64

    # gcc-6 32
    - env: GCC_VERSION=6 BUILD_TYPE=Debug ARCH=32
      os: linux
      addons: &gcc6-32
        apt:
          packages:
            - cmake
            - cmake-data
            - rpm
            - linux-libc-dev:i386
            - g++-6-multilib
            - gcc-6-multilib
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
    - env: GCC_VERSION=6 BUILD_TYPE=Release ARCH=32
      os: linux
      addons: *gcc6-32

    # gcc-6 64
    - env: GCC_VERSION=6 BUILD_TYPE=Debug ARCH=64
      os: linux
      addons: &gcc6-64
        apt:
          packages:
            - cmake
            - cmake-data
            - rpm
            - g++-6
            - gcc-6
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
    - env: GCC_VERSION=6 BUILD_TYPE=Release ARCH=64
      os: linux
      addons: *gcc6-64
  allow_failures:
    - os: osx

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

before_install:
  - |
    if [ -n "$GCC_VERSION" ]; then
      export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}" GCOV="gcov-${GCC_VERSION}";
    fi
  - |
    if [ -n "$CLANG_VERSION" ]; then
      export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}";
    fi


install:
  # install latest LCOV (1.9 was failing)
  - |
    if [[ $TRAVIS_OS_NAME != "osx" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
      tar xf lcov_1.11.orig.tar.gz
      sudo make -C lcov-1.11/ install
      gem install coveralls-lcov
      lcov --version
    fi

before_script:
  #- if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update > /dev/null && brew install mariadb && mysql.server start; fi
  - mkdir build
  - cd build
  - |
    if [[ "$GCOV" == "gcov-5" && "$BUILD_TYPE" == "Debug" ]]; then
      cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DARCH=${ARCH} -DGCOV_BINARY=${GCOV} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCOVERAGE=true ..;
      lcov --directory include --directory src --directory test --zerocounters
    else
      cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DARCH=${ARCH} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..;
    fi

script:
  - |
      make
      make check

after_success:
  - |
    if [[ $GCOV == "gcov-5" && "$BUILD_TYPE" == "Debug" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      type $GCOV
      lcov --no-external --base-directory ${TRAVIS_BUILD_DIR} --directory build/src --directory build/test --capture --gcov-tool `which $GCOV` --output-file coverage.info
      lcov --remove coverage.info 'build/test/*' 'build/src/*' --gcov-tool `which $GCOV` --output-file coverage.info
      lcov --list coverage.info
      coveralls-lcov --repo-token=${COVERALLS_TOKEN} coverage.info
    fi

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake --build build --target archpkg
  - cmake --build build --target package
  - export RELEASE_TGZ_FILE=$(ls Package/*.tar.gz)
  - export RELEASE_DEB_FILE=$(ls Package/*.deb)
  - export RELEASE_RPM_FILE=$(ls Package/*.rpm)
  - export RELEASE_PKG_FILE=$(ls Package/*.pkg.tar.xz)
  - echo "deploying $RELEASE_TGZ_FILE, $RELEASE_DEB_FILE $RELEASE_PKG_FILE and $RELEASE_RPM_FILE to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: "tcYHoQKYGE2//w4xTdPLnZDcwahb9GAnrHDGr3NXWf/ygYRb8uwncthLcBA1nV0TTwI7mOe70Ylr6ZpRopuqNCsamBQUTs3Doc8PNdkkZPRhJRdfU9Tuf2RdONOF+yIBuKaH8RrLcFOL7ZZtwmzKMFLwAYwOUt7Y9YA/OWqAKm2RAyE4xHAb5pFJ1qsdK5Md4bnAFhehYSqOlkHTziE/AAnWBxt5FTNvPumZy2eIl6NlRiJZLYz4h6jvcCswiO/sgGKTekXIa6lX9+dPg1PATBORRaJknETARreK0pg9u9giF98ewAAhtE4d1a/WMV03XGiecQ/EBideHTOwKtLnrRLZAlO5M/daQHHmd1szHivwerEJOX0MdFbSYlOS565nUJInOE3xYWxk4axqlKrB3QDdYglPqX0jF2pDxmueh1fkHquea2YPkzRIKbjYDAALp67AdXC6Ujwi5QaV+7d5vuWLbmlpXfROAbRku+4t2U1+7XdKs+5QL6p8UqmaJFmyjziAGFy2wVbq4/yaOg0h5nBBIHmPMwywO310I5dSXEmErdN3Wx93nf+V6rzFC5IiwnNHIna54gqIp5AZRrumG+76cJHE/Xn4QPGdpu6Hg0pvMurFoH0xI9bpK+eID2HALrq7knpDFXckcyNWfINANuD++qyCXLfDn+qKxRu9ujc="
  file:
    - "${RELEASE_TGZ_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
    - "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
    condition: "$GCC_VERSION = 6 && $BUILD_TYPE = Release"
    all_branches: true

notifications:
  email:
    recipients:
      - sascha.kuehl@gmx.net
