version: "{build}"

#services:
#  - mssql2014
#  - mysql

image: Visual Studio 2015

configuration:
  - Debug
  - Release

environment:
  matrix:
  - VS_VERSION: Visual Studio 14 2015
  - VS_VERSION: Visual Studio 14 2015 Win64

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

before_build:
  - mkdir build
  - cd build
  - cmake -G "%VS_VERSION%" -DCMAKE_BUILD_TYPE=%configuration% ..

build_script:
  - cmake --build . --config %configuration% --target check

test_script:
  - ctest --verbose

after_build:
  - ps: |
      if (($env:APPVEYOR_REPO_TAG -Match "true") -and ($env:configuration -Match "Release")) {
        cpack -G NSIS -C Release
        cpack -G ZIP -C Release
      }

artifacts:
  - path: Package/calc*.exe
    name: installer
  - path: Package/calc*.zip
    name: zipper

deploy:
  provider: GitHub
  auth_token:
    secure: "tcYHoQKYGE2//w4xTdPLnZDcwahb9GAnrHDGr3NXWf/ygYRb8uwncthLcBA1nV0TTwI7mOe70Ylr6ZpRopuqNCsamBQUTs3Doc8PNdkkZPRhJRdfU9Tuf2RdONOF+yIBuKaH8RrLcFOL7ZZtwmzKMFLwAYwOUt7Y9YA/OWqAKm2RAyE4xHAb5pFJ1qsdK5Md4bnAFhehYSqOlkHTziE/AAnWBxt5FTNvPumZy2eIl6NlRiJZLYz4h6jvcCswiO/sgGKTekXIa6lX9+dPg1PATBORRaJknETARreK0pg9u9giF98ewAAhtE4d1a/WMV03XGiecQ/EBideHTOwKtLnrRLZAlO5M/daQHHmd1szHivwerEJOX0MdFbSYlOS565nUJInOE3xYWxk4axqlKrB3QDdYglPqX0jF2pDxmueh1fkHquea2YPkzRIKbjYDAALp67AdXC6Ujwi5QaV+7d5vuWLbmlpXfROAbRku+4t2U1+7XdKs+5QL6p8UqmaJFmyjziAGFy2wVbq4/yaOg0h5nBBIHmPMwywO310I5dSXEmErdN3Wx93nf+V6rzFC5IiwnNHIna54gqIp5AZRrumG+76cJHE/Xn4QPGdpu6Hg0pvMurFoH0xI9bpK+eID2HALrq7knpDFXckcyNWfINANuD++qyCXLfDn+qKxRu9ujc="
  artifact: installer,zipper
  draft: false
  prerelease: false
  on:
    configuration: Release
    appveyor_repo_tag: true