version: "{build}"

#services:
#  - mssql2014
#  - mysql

image: Visual Studio 2015

configuration:
  - Debug
  - Release

environment:
  matrix:
  - VS_VERSION: Visual Studio 14 2015
  - VS_VERSION: Visual Studio 14 2015 Win64

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

before_build:
  - mkdir build
  - cd build
  - cmake -G "%VS_VERSION%" -DCMAKE_BUILD_TYPE=%configuration% ..

build_script:
  - cmake --build . --config %configuration% --target check

test_script:
  - ctest --verbose

after_build:
  - ps: |
      if (($env:APPVEYOR_REPO_TAG -Match "true") -and ($env:configuration -Match "Release")) {
        cpack -G NSIS -C Release
        cpack -G ZIP -C Release
      }

artifacts:
  - path: Package/calc*.exe
    name: installer
  - path: Package/calc*.zip
    name: zipper

deploy:
  provider: GitHub
  auth_token:
    secure: re/Z5Ya8IXvuJI4PLD5y6AkuX/yLqEXXxzEwP5pYTJyuIEo5eK4TLMYX7OVP5QGMnuYSv5o3EMXbU30XZpL2z8L+e3lxG0xohRPRjZj8sRHnqwIha+0bbVJc2ufXD3Pml1oAp109SbLHlRiypW06Uv+EEEGtqXayXlGlxziRZA3/Hvz5KmiV5TECrMBg1zHuWT1mRCr5XV9vMjB/HyayW77gxVGL+ox3jZxywwuKf9gMn92f9iQMy8FvaP1Fj7JqBah/Bb4MVPHHGoaq7WDho1inw4/C+YX+gJu/AgMasY/n8l4MjqHp+WBUBN+EBCPfIp4jonkrZGws9E/VqhEHCQQ+MVGj5wQljuD4Ea968aErbX6q/r7toom05/z+16YaTtOJDA5QQkj6YARbtQ8Ulktqj9hEZKs9msHXtGxmwVifn4TMgXuxg9n/2fxoveThrwDYuhSL95jsU+baQiLng2CKVhJAY3wQWiYkua2THZLe5JY3n8kwQB7FiVaNMZ1oBooNG2tsQq0B1a7/cwj3TLc18q7rrkVL8TpDeW15LBV+NUywwZOECmnkfCAAgzU3dRovcdTBlXW0DeSNYy0APykT+He44c5ktFnolO9uSwN7jpCJ2PWESQSg+BmjewrxOx666vivu1COvESn74Ew5PBpnyUrOb2PYf53IrpJCPE=
  artifact: installer,zipper
  draft: false
  prerelease: false
  on:
    configuration: Release
    appveyor_repo_tag: true