version: "{build}"

#services:
#  - mssql2014
#  - mysql

image: Visual Studio 2015

configuration:
  - Debug
  - Release

environment:
  matrix:
  - VS_VERSION: Visual Studio 14 2015
  - VS_VERSION: Visual Studio 14 2015 Win64

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

before_build:
  - mkdir build
  - cd build
  - cmake -G "%VS_VERSION%" -DCMAKE_BUILD_TYPE=%configuration% ..

build_script:
  - cmake --build . --config %configuration%

test_script:
  - ctest --verbose

after_build:
  - ps: |
      if (($env:APPVEYOR_REPO_TAG -Match "true") -and ($env:configuration -Match "Release")) {
        cpack -G NSIS -C Release
      }

artifacts:
  - path: Package/calc*.exe

deploy:
  provider: GitHub
  auth_token:
    secure: "kz/25t/c0oeOJ3Ux3r+Sy5F4G7YgPmjSrTpgZ73IQDY4N9mYNqH4kAv4+0I0oeh6"
  artifact: /Package\/calc.*\.exe/
  draft: false
  prerelease: false
  on:
    configuration: Release
    appveyor_repo_tag: true